CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description CLOB NOT NULL,
    topic VARCHAR(150) NOT NULL,
    asked_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE question_tags (
    question_id BIGINT NOT NULL,
    tag VARCHAR(100) NOT NULL,
    CONSTRAINT fk_question_tags_question FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- H2 2.x does not support functional indexes in simple CREATE INDEX statements,
-- so rely on a standard index and let Spring Data handle case-insensitive queries.
CREATE INDEX idx_question_topic ON questions (topic);
CREATE INDEX idx_question_asked_by ON questions (asked_by);
