CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id VARCHAR(100) NOT NULL,
    sender_name VARCHAR(150) NOT NULL,
    sender_id VARCHAR(150) NOT NULL,
    content VARCHAR(500) NOT NULL,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chat_room_time ON chat_messages (room_id, sent_at);
